//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0")]
[assembly: AssemblyInformationalVersion("1.0.0--1")]
#if !PORTABLE
[assembly: AssemblyMetadata("BuildDateUtc", @"2015-06-28T07:29:52.089Z")]
#endif
