FROM debian:8
LABEL vendor=automotiveMastermind\ and\ Contributors

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        libicu52 \
        libcurl3 \
        libunwind8 \
        locales \
        curl \
        tar \
        git \
    && rm -rf /var/lib/apt/lists/* \
    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8

ENV LANG en_US.UTF-8

ARG source=.
ARG destination=/condo
WORKDIR $destination

COPY $source .
COPY $source/.docker/docker-task.sh /

ENTRYPOINT ["/docker-task.sh"]
CMD [ "condo", "/t:test" ]
