//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.36.354")]
[assembly: AssemblyInformationalVersion("1.0.0-alpha-00036-0354")]
[assembly: AssemblyMetadata("BuildDateUtc", @"2015-07-05T03:54:20.897Z")]
[assembly: AssemblyMetadata("Branch", @"refs/heads/feature/12-buildtests")]
[assembly: AssemblyMetadata("BuildId", @"36")]
[assembly: AssemblyMetadata("CommitId", @"27e09d4cd33362ecfafd3457dd8221397dcf6d33")]
[assembly: AssemblyMetadata("BuiltBy", @"dmccaffery@pulsebridge.com")]
[assembly: AssemblyMetadata("BuiltOn", @"gio-ws-01.local")]
[assembly: AssemblyMetadata("RepositoryUri", @"https://dmccaffery-pb.visualstudio.com/defaultcollection/open/_git/condo")]