//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.70415")]
[assembly: AssemblyInformationalVersion("1.0.0-alpha-070415-2247")]
[assembly: AssemblyMetadata("BuildDateUtc", @"2015-07-04T22:47:53.856Z")]
[assembly: AssemblyMetadata("Branch", @"refs/heads/feature/17-testall")]
[assembly: AssemblyMetadata("BuildId", @"070415")]
[assembly: AssemblyMetadata("CommitId", @"ede6cdd87ccb1f5ebcae6f1dc68c8afef0dec30c")]
[assembly: AssemblyMetadata("BuiltBy", @"dmccaffery@pulsebridge.com")]
[assembly: AssemblyMetadata("BuiltOn", @"gio-ws-01.local")]
[assembly: AssemblyMetadata("RepositoryUri", @"https://dmccaffery-pb.visualstudio.com/defaultcollection/open/_git/condo")]