//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.37.1744")]
[assembly: AssemblyInformationalVersion("1.0.0-alpha-00037-1744")]
[assembly: AssemblyMetadata("BuildDateUtc", @"2015-07-05T17:44:31.995Z")]
[assembly: AssemblyMetadata("Branch", @"refs/heads/feature/12-buildtests")]
[assembly: AssemblyMetadata("BuildId", @"37")]
[assembly: AssemblyMetadata("CommitId", @"706d1178b7740b62f9da0f714a6076d6d66eeeb5")]
[assembly: AssemblyMetadata("BuiltBy", @"dmccaffery@pulsebridge.com")]
[assembly: AssemblyMetadata("BuiltOn", @"gio-ws-01.local")]
[assembly: AssemblyMetadata("RepositoryUri", @"https://dmccaffery-pb.visualstudio.com/defaultcollection/open/_git/condo")]