FROM fedora:23
LABEL vendor=automotiveMastermind\ and\ Contributors

ENV destination /condo
ENV LANG C.UTF-8

ARG source=.
WORKDIR $destination

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        libicu52 \
        libcurl3 \
        libunwind8 \
        curl \
        tar \
        git \
    && rm -rf /var/lib/apt/lists/*

COPY $source/test/.docker/docker-task.sh /
COPY $source .

ENTRYPOINT ["/docker-task.sh"]
CMD [ "condo", "/t:ci" ]
