FROM fedora:24
LABEL vendor=automotiveMastermind\ and\ Contributors

ENV destination /condo
ENV LANG C.UTF-8

ARG source=.
WORKDIR $destination

RUN dnf -y update && dnf clean all
RUN dnf install -y \
        ca-certificates \
        curl \
        tar \
        git \
    && dnf clean all

COPY $source/test/.docker/docker-task.sh /
COPY $source .

ENTRYPOINT ["/docker-task.sh"]
CMD [ "condo", "/t:ci" ]
