//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.70515")]
[assembly: AssemblyInformationalVersion("1.0.0-alpha-070515-0237")]
#if !PORTABLE
[assembly: AssemblyMetadata("Branch", @"refs/heads/feature/12-buildtests")]
[assembly: AssemblyMetadata("BuildId", @"070515")]
[assembly: AssemblyMetadata("CommitId", @"2d89efa9fa0c1f160a42c0d8dee2e6ff035dfbe1")]
[assembly: AssemblyMetadata("BuildDateUtc", @"2015-07-05T02:37:24.162Z")]
[assembly: AssemblyMetadata("BuiltBy", @"dmccaffery@pulsebridge.com")]
[assembly: AssemblyMetadata("BuiltOn", @"gio-ws-01.local")]
[assembly: AssemblyMetadata("RepositoryUri", @"https://dmccaffery-pb.visualstudio.com/defaultcollection/open/_git/condo")]
#endif
