//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;


[assembly: AssemblyProduct(@"PulseBridge.Condo")]
[assembly: AssemblyCompany(@"PulseBridge, Inc.")]
[assembly: AssemblyCopyright(@"© 2015. PulseBridge, Inc. All rights reserved.")]
[assembly: AssemblyVersion(@"1.0.0.0")]
[assembly: AssemblyFileVersion(@"1.0.42.450")]
[assembly: AssemblyInformationalVersion(@"1.0.0-alpha-00042-0450")]
[assembly: AssemblyMetadata("BuildDateUtc", @"2015-07-08T04:50:33.970Z")]
[assembly: AssemblyMetadata("Branch", @"refs/heads/feature/23-cibuildid")]
[assembly: AssemblyMetadata("BuildId", @"42")]
[assembly: AssemblyMetadata("CommitId", @"4d8ad9fc112531cbbf1a0bf0e42d6c43e8e91039")]
[assembly: AssemblyMetadata("BuiltBy", @"dmccaffery@pulsebridge.com")]
[assembly: AssemblyMetadata("BuiltOn", @"gio-ws-01.local")]
[assembly: AssemblyMetadata("RepositoryUri", @"https://dmccaffery-pb.visualstudio.com/defaultcollection/open/_git/condo")]
[assembly: AssemblyMetadata("License", @"Apache License, Version 2.0")]
[assembly: AssemblyMetadata("LicenseUri", @"http://www.apache.org/licenses/LICENSE-2.0")]