FROM microsoft/dotnet:2-sdk

WORKDIR /condo
COPY ${CONDO:-obj/docker/publish/netcoreapp2.1/linux-x64} .
RUN chmod +x docker.sh

# Run condo
ENTRYPOINT [ "./docker.sh" ]
CMD [ "condo", "--", "/t:ci" ]
