FROM microsoft/vsts-agent:ubuntu-16.04

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        curl \
        dnsutils \
        file \
        ftp \
        iproute2 \
        iputils-ping \
        locales \
        openssh-client \
        rsync\
        shellcheck \
        sudo \
        telnet \
        time \
        unzip \
        wget \
        zip \
        tzdata \
        cron \
    && rm -rf /var/lib/apt/lists/* 1>/dev/null

RUN echo 'en_US.UTF-8 UTF-8' > /etc/locale.gen \
    && locale-gen

ENV LANGUAGE=en_US.UTF-8 \
    LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8

RUN update-locale

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
    && rm -rf /var/lib/apt/lists/* 1>/dev/null

ENV DOTNET_2_1_VERSION=2.1.6
ARG DOTNET_2_1_SHA=74D99AEFCBE953B30743330689E750156E68C3410BC26C40A11B60BBBF1D01887262BD6D7C0EEACCA4D6B696C1A04980D9BE2DC2A222226FA910B885D2FB5956

RUN curl -SL --output dotnet.tar.gz https://dotnetcli.blob.core.windows.net/dotnet/Runtime/$DOTNET_2_1_VERSION/dotnet-runtime-$DOTNET_2_1_VERSION-linux-x64.tar.gz \
    && echo "$DOTNET_2_1_SHA dotnet.tar.gz" | sha512sum -c - \
    && mkdir -p /usr/share/dotnet \
    && tar -zxf dotnet.tar.gz -C /usr/share/dotnet \
    && rm dotnet.tar.gz 1>/dev/null

ENV DOTNET_SDK_VERSION=2.2.101 \
    DOTNET_VERSION=2.2.0 \
    DOTNET_CURRENT_VERSION=2.2.0

ARG DOTNET_SDK_SHA=7D0235469287D55B87AA68FDD8CCE51D2F35FDCCE485701EBF14B53E3AE0A341CDAB8D04AAE066F5E4EBD1BCA7A55C18016DEC4643DE72FD2321FE81C9CB69CD

RUN curl -SL --output dotnet.tar.gz https://dotnetcli.blob.core.windows.net/dotnet/Sdk/$DOTNET_SDK_VERSION/dotnet-sdk-$DOTNET_SDK_VERSION-linux-x64.tar.gz \
    && echo "$DOTNET_SDK_SHA dotnet.tar.gz" | sha512sum -c - \
    && mkdir -p /usr/share/dotnet \
    && tar -zxf dotnet.tar.gz -C /usr/share/dotnet \
    && rm dotnet.tar.gz 1>/dev/null \
    && ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet

ENV ASPNETCORE_URLS=http://+:80 \
    DOTNET_RUNNING_IN_CONTAINER=true \
    DOTNET_USE_POLLING_FILE_WATCHER=true \
    NUGET_XMLDOC_MODE=skip \
    DOTNET_CLI_TELEMETRY_OPTOUT=1

RUN dotnet help
RUN dotnet --info

ARG CONDO_SOURCE=obj/docker/publish/netcoreapp2.1/any

COPY $CONDO_SOURCE /root/.am/condo
RUN chmod +x /root/.am/condo/docker.sh \
    && chmod +x /root/.am/condo/cli.sh \
    && chmod -R ugo=r,+x /root/.am/condo \
    && ln -s /root/.am/condo/cli.sh /usr/bin/condo

ENV dotnet=/usr/bin/dotnet \
    dotnet2=/usr/bin/dotnet \
    condo=/usr/bin/condo

COPY $CONDO_SOURCE/docker-gc.sh /etc/cron.hourly/docker-gc
RUN chmod u=rwx,g=rw,o=rw /etc/cron.hourly/docker-gc

ENTRYPOINT [ "/root/.am/condo/docker.sh" ]
CMD [ "agent" ]
