FROM microsoft/vsts-agent:ubuntu-16.04

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    curl \
    dnsutils \
    file \
    ftp \
    iproute2 \
    iputils-ping \
    locales \
    openssh-client \
    rsync\
    shellcheck \
    sudo \
    telnet \
    time \
    unzip \
    wget \
    zip \
    tzdata \
 && rm -rf /var/lib/apt/lists/*

RUN echo 'en_US.UTF-8 UTF-8' > /etc/locale.gen \
    && locale-gen

ENV LANGUAGE=en_US.UTF-8 \
    LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8

RUN update-locale

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
    && rm -rf /var/lib/apt/lists/*

ENV DOTNET_SDK_VERSION=2.1.402 \
    DOTNET_VERSION=2.1.4 \
    DOTNET_CURRENT_VERSION=2.1.4

ARG DOTNET_CURRENT_SHA=dd7f15a8202ffa2a435b7289865af4483bb0f642ffcf98a1eb10464cb9c51dd1d771efbb6120f129fe9666f62707ba0b7c476cf1fd3536d3a29329f07456de48

RUN curl -SL --output dotnet.tar.gz https://dotnetcli.blob.core.windows.net/dotnet/Sdk/$DOTNET_SDK_VERSION/dotnet-sdk-$DOTNET_SDK_VERSION-linux-x64.tar.gz \
    && echo "$DOTNET_CURRENT_SHA dotnet.tar.gz" | sha512sum -c - \
    && mkdir -p /usr/share/dotnet \
    && tar -zxf dotnet.tar.gz -C /usr/share/dotnet \
    && rm dotnet.tar.gz \
    && ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet

ENV ASPNETCORE_URLS=http://+:80 \
    DOTNET_RUNNING_IN_CONTAINER=true \
    DOTNET_USE_POLLING_FILE_WATCHER=true \
    NUGET_XMLDOC_MODE=skip \
    DOTNET_CLI_TELEMETRY_OPTOUT=1

RUN dotnet help
RUN dotnet --info

ARG CONDO_SOURCE=obj/docker/publish/netcoreapp2.1/any
ARG CONDO_TARGET=/root/.am/condo

COPY $CONDO_SOURCE $CONDO_TARGET
RUN chmod +x $CONDO_TARGET/docker.sh \
    && chmod +x $CONDO_TARGET/cli.sh \
    && chmod -R ugo=r,+x $CONDO_TARGET \
    && ln -s $CONDO_TARGET/cli.sh /usr/bin/condo

ENV DOTNET_SDK_VERSION=2.1.402 \
    DOTNET_VERSION=2.1.4 \
    DOTNET_CURRENT_VERSION=2.1.4 \
    dotnet=/usr/bin/dotnet \
    dotnet_2=/usr/bin/dotnet \
    condo=/usr/bin/condo
