FROM microsoft/vsts-agent:ubuntu-16.04-docker-17.12.0-ce

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    curl \
    dnsutils \
    file \
    ftp \
    iproute2 \
    iputils-ping \
    locales \
    openssh-client \
    rsync\
    shellcheck \
    sudo \
    telnet \
    time \
    unzip \
    wget \
    zip \
    tzdata \
    cron \
 && rm -rf /var/lib/apt/lists/*

RUN echo 'en_US.UTF-8 UTF-8' > /etc/locale.gen \
    && locale-gen

ENV LANGUAGE=en_US.UTF-8 \
    LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8

RUN update-locale

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
    && rm -rf /var/lib/apt/lists/*

ENV DOTNET_SDK_VERSION=2.1.500 \
    DOTNET_VERSION=2.1.4 \
    DOTNET_CURRENT_VERSION=2.1.4

ARG DOTNET_SDK_SHA=85055728E2433DFDE41D15C85475F2DC6CFDD30242B4B23065B63CB12CC846ACB93C09C000B02B722890CEAC8AC382B40871C78660716CA2339C71052FE52F4E

RUN curl -SL --output dotnet.tar.gz https://dotnetcli.blob.core.windows.net/dotnet/Sdk/$DOTNET_SDK_VERSION/dotnet-sdk-$DOTNET_SDK_VERSION-linux-x64.tar.gz \
    && echo "$DOTNET_SDK_SHA dotnet.tar.gz" | sha512sum -c - \
    && mkdir -p /usr/share/dotnet \
    && tar -zxf dotnet.tar.gz -C /usr/share/dotnet \
    && rm dotnet.tar.gz \
    && ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet

ENV ASPNETCORE_URLS=http://+:80 \
    DOTNET_RUNNING_IN_CONTAINER=true \
    DOTNET_USE_POLLING_FILE_WATCHER=true \
    NUGET_XMLDOC_MODE=skip \
    DOTNET_CLI_TELEMETRY_OPTOUT=1

RUN dotnet help
RUN dotnet --info

ARG CONDO_SOURCE=obj/docker/publish/netcoreapp2.1/any

COPY $CONDO_SOURCE /root/.am/condo
RUN chmod +x /root/.am/condo/docker.sh \
    && chmod +x /root/.am/condo/cli.sh \
    && chmod -R ugo=r,+x /root/.am/condo \
    && ln -s /root/.am/condo/cli.sh /usr/bin/condo

ENV dotnet=/usr/bin/dotnet \
    dotnet2=/usr/bin/dotnet \
    condo=/usr/bin/condo \
    docker=/usr/local/bin/docker \
    docker_compose=/usr/local/bin/docker-compose

COPY $CONDO_SOURCE/docker-gc.sh /etc/cron.hourly
RUN chmod u=rwx,g=rw,o=rw /etc/cron.hourly/docker-gc.sh

ENTRYPOINT [ "/root/.am/condo/docker.sh" ]
CMD [ "agent" ]
