FROM microsoft/dotnet:1.1.2-sdk-jessie

ENV SKIP_DOTNET_INSTALL = "true"
ENV SKIP_CONDO_PUBLISH = "true"
ARG cli=./artifacts/publish/
ARG src=./src/AM.Condo

WORKDIR root/.am/condo
COPY $cli ./cli
COPY $src ./.src

WORKDIR /app
